--Find total revenue is generated by each customer
SELECT SUM(sa.Price)-SUM(pr.Product_cost) revenue_for_each_customer
	  ,cu.Customer_id
FROM  gold.fact_salse sa
 LEFT JOIN gold.dim_prd pr
ON sa.Product_key=pr.Product_key
 LEFT JOIN gold.dim_customers cu
ON sa.Customer_Key=cu.Customer_Key
GROUP BY cu.Customer_id;